# Generated by Django 5.2 on 2025-05-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'credit'), ('return', 'return')], max_length=10),
        ),
    ]
