# Generated by Django 5.2 on 2025-05-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_photo',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_photo_mime',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
